# Generated by Django 3.2.7 on 2021-09-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210910_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/500x500.png?text=Default', upload_to='course\\images'),
        ),
    ]
