# Generated by Django 3.2.7 on 2021-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cartJson',
            new_name='jsonCart',
        ),
        migrations.AlterField(
            model_name='order',
            name='isSameBillingAddress',
            field=models.BooleanField(default='false'),
        ),
    ]
